### ISSUE TITLE
Unity example?

### ISSUE THREAD

**Issue by Sean-Zeo** [bp2008/x264net#4]
Hi friend, any example of this working in Unity3D?
Thanks.

**Comment by bp2008** [comment]
This library uses C++/CLI for the interoperability with native code.  I don't think Unity works with C++/CLI because that requires official .NET Framework, but Unity uses Mono instead.  I don't know of any simple alternatives, though there does exist https://code.videolan.org/videolan/LibVLCSharp it might be limited in which platforms it can run on.
